name = "OpticalDatasets"
uuid = "a0fc030c-aaa4-4e24-9fdc-1cbe49ce0bda"
version = "0.1.0-DEV"
authors = ["Alex S. Gardner, JPL/NASA"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"

[compat]
ArchGDAL = "0.10"
Dates = "1"
DiskArrays = "0.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
